# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
    name: LinuxBuild

steps:
- checkout: self
- task: Bash@3
  displayName: 'install ansible galaxy if not installed'
  inputs:
    targetType: inline
    script: >-
      sudo apt-get update

      sudo apt-get install python3-pip git libffi-dev libssl-dev -y
      
      sudo apt-get install ansible -y

      pip3 install pywinrm
      
    failOnStderr: true