- name: Manage Hyper-V and create VM's
  hosts: all
  tasks:
    - name: Stop VM
      win_hyperv_guest:
        name: "{{ item }}"
        state: stopped
      loop: "{{ vmstopped }}"
    - name: Start VM
      win_hyperv_guest:
        name: "{{ item }}"
        state: started
      loop: "{{ vmstarted }}"